### ISSUE TITLE
Test fails on Windows with non-latin folders

### ISSUE THREAD

**Issue by tainkrios** [hplush/slowreader#103]
After installing environments and run `pnpm test` I get this output:
```bash

> slowreader@ test /mnt/c/Users/taink/OneDrive/Документы/projects/slowreader
> FORCE_COLOR=1 pnpm run -r --include-workspace-root /^test:/

Scope: all 6 workspace projects
[36m.[39m [96mtest:js[39m$ eslint .
[36m.[39m [96mtest:types[39m$ svelte-check
[36m.[39m [96mtest:focused[39m$ tsx ./scripts/check-focused-tests.ts
[36m.[39m [96mtest:audit[39m$ pnpm audit --prod
[36m.[39m [96mtest:focused[39m: [90mnode:internal/process/esm_loader:34[39m
[36m.[39m [96mtest:focused[39m: [90m      internalBinding('errors').triggerUncaughtException([39m
[36m.[39m [96mtest:focused[39m: [90m                                ^[39m
[36m.[39m [96mtest:focused[39m: [90mTypeError [Error]: undefined is not iterable (cannot read property Symbol(Symbol.iterator))[39m
[36m.[39m [96mtest:focused[39m: [90m    at bt [90m(file:///mnt/c/Users/taink/OneDrive/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/projects/slowreader/[39m[90mnode_modules/[4m.pnpm[24m/tsx@4.7.1/node_modules/[4mtsx[24m/dist/index-29948669.mjs:16:1598[90m)[39m[90m[39m
[36m.[39m [96mtest:focused[39m: [90m    at [90mfile:///mnt/c/Users/taink/OneDrive/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/projects/slowreader/[39m[90mnode_modules/[4m.pnpm[24m/tsx@4.7.1/node_modules/[4mtsx[24m/dist/index-29948669.mjs:17:632[39m
[36m.[39m [96mtest:focused[39m: [90m    at hr [90m(file:///mnt/c/Users/taink/OneDrive/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/projects/slowreader/[39m[90mnode_modules/[4m.pnpm[24m/tsx@4.7.1/node_modules/[4mtsx[24m/dist/index-29948669.mjs:16:1071[90m)[39m[90m[39m
[36m.[39m [96mtest:focused[39m: [90m    at Cr [90m(file:///mnt/c/Users/taink/OneDrive/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/projects/slowreader/[39m[90mnode_modules/[4m.pnpm[24m/tsx@4.7.1/node_modules/[4mtsx[24m/dist/index-29948669.mjs:17:560[90m)[39m[90m[39m
[36m.[39m [96mtest:focused[39m: [90m    at Z [90m(file:///mnt/c/Users/taink/OneDrive/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/projects/slowreader/[39m[90mnode_modules/[4m.pnpm[24m/tsx@4.7.1/node_modules/[4mtsx[24m/dist/esm/index.mjs:5:1755[90m)[39m[90m[39m
[36m.[39m [96mtest:focused[39m: [90m[90m    at async nextLoad (node:internal/modules/esm/hooks:865:22)[39m[90m[39m
[36m.[39m [96mtest:focused[39m: [90m[90m    at async Hooks.load (node:internal/modules/esm/hooks:448:20)[39m[90m[39m
[36m.[39m [96mtest:focused[39m: [90m[90m    at async MessagePort.handleMessage (node:internal/modules/esm/worker:196:18)[39m[90m[39m
[36m.[39m [96mtest:focused[39m: [90mNode.js v20.11.1[39m
[36m.[39m [96mtest:focused[39m: Failed
[41m[30m ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL [39m[49m [31mslowreader@ test:focused: `tsx ./scripts/check-focused-tests.ts`[39m
[31mExit status 1[39m
[36m.[39m [96mtest:messages[39m$ tsx ./scripts/check-messages.ts
 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by ai** [comment]
Let’s try:

1. Show `node -v` and `pnpm -v`. Maybe shell is using old Node.js because of some error.
2. Try to move project to path with only-English letters (`OneDrive/Документы/projects/slowreader` → `OneDrive/slowreader`)

**Comment by tainkrios** [comment]
Yes, changing the directory helped. Thank you.

**Comment by ai** [comment]
Can you send PR to `CONTRIBUTION.md` with the note about non-Latin folders?

**Comment by tainkrios** [comment]
ok, is there any convention about branch names?

**Comment by ai** [comment]
> ok, is there any convention about branch names?

No.

We can add it too, since many people ask.

**Comment by ai** [comment]
I changed issue title to make it easy to find it later
